# Generated by Django 5.2.10 on 2026-01-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('total_movies', models.IntegerField(default=0)),
                ('processed_movies', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('original_language', models.CharField(max_length=10)),
                ('overview', models.TextField(blank=True)),
                ('adult', models.BooleanField(default=False)),
                ('video', models.BooleanField(default=False)),
                ('popularity', models.FloatField(default=0.0)),
                ('vote_average', models.FloatField(default=0.0)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.ImageField(blank=True, null=True, upload_to='movies/posters/')),
                ('backdrop_path', models.ImageField(blank=True, null=True, upload_to='movies/backdrops/')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
            ],
        ),
    ]
