# Generated by Django 5.2.10 on 2026-01-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetchtaskstatus',
            name='processed_movies',
        ),
        migrations.RemoveField(
            model_name='fetchtaskstatus',
            name='updated_at',
        ),
    ]
