# Generated by Django 5.2.10 on 2026-01-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FetchTaskStatus',
            new_name='Status',
        ),
    ]
