# Generated by Django 5.2.10 on 2026-01-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_fetchtaskstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_language',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
